Ccp 1209
shopgate-professional-services/ext-shopify-back-in-stock pull request #1
Opened 2019-03-05 17:23 UTC by aaron-martin

2019-03-28 08:51 UTC, sznowicki requested changes
.

2019-03-28 08:51 UTC, sznowicki commented on frontend/reducers/index.js
> +        ...state,
Default should never return a copy of state. This way it will not give selectors an opportunity to memoise.

2019-03-28 08:51 UTC, sznowicki commented on .editorconfig
> +# To use .editorconfig you need to install a plugin from
I'll put all the bugs here so we can have civilised discussion

2019-03-28 08:51 UTC, sznowicki commented on .editorconfig
> +# To use .editorconfig you need to install a plugin from
![Screenshot 2019-03-27 at 16 45 34](https://user-images.githubusercontent.com/3393569/55090679-d126f180-50af-11e9-8e67-06f73fcd750f.png)

Default confirmtion text looks wrong (trailing T)

2019-03-28 08:51 UTC, sznowicki commented on .editorconfig
> +# To use .editorconfig you need to install a plugin from
![Screenshot 2019-03-27 at 16 45 03](https://user-images.githubusercontent.com/3393569/55090725-e13ed100-50af-11e9-82c6-a02d7a49b493.png)

I think there's no reason to have confirm/cancel buttons in this modal

2019-03-28 08:51 UTC, sznowicki commented on .editorconfig
> +# To use .editorconfig you need to install a plugin from
I've found that it only works for simple products. If user selects a variant which is not in stock, the feature is still hidden.

Tested with Iron Man Hoodie

2019-03-29 15:25 UTC, aaron-martin commented on frontend/reducers/index.js
> +        ...state,
I think I have this done.

2019-03-29 15:32 UTC, aaron-martin commented on .editorconfig
> +# To use .editorconfig you need to install a plugin from
Fixed German translation string, modified modal accept button, corrected issue with variant products.

2019-04-01 11:33 UTC, sznowicki requested changes

2019-04-01 11:33 UTC, sznowicki commented on .editorconfig
> +# To use .editorconfig you need to install a plugin from
Well, AFAIK we have consistent upper case button texts. So "ok" or "okay" is not an option. Please Adjust it to "OK" / "Okay" or simply use PWA locales `modal.ok`

2019-04-01 15:00 UTC, sznowicki approved these changes

2019-04-01 15:00 UTC, merged